# Generated by Django 2.0.6 on 2018-06-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akvatorii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAkvatorii', models.CharField(max_length=100)),
                ('changed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Osadki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('otschot', models.FloatField()),
                ('popravka', models.FloatField()),
                ('changed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TochkiSbora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('stationType', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('otn', models.PositiveSmallIntegerField()),
                ('akvatorii', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.Akvatorii')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Osadki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOsadki', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='osadki',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.TochkiSbora'),
        ),
        migrations.AddField(
            model_name='osadki',
            name='type_osadki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculation.Type_Osadki'),
        ),
    ]
